import type { StampPreset } from './types.js';
import { PALETTES } from './themes.js';
import { getCurrentPostalDate } from './stampRenderer.js';

export const STAMP_PRESETS: StampPreset[] = [
  {
    id: 'delhi-airmail',
    name: 'Delhi Airmail',
    description: 'Prussian Blue with harmonic guilloche security waves',
    config: {
      fromLocation: 'Delhi',
      toLocation: 'Paris',
      code: 'DL',
      codePlacement: 'top-left',
      denomination: '25¢',
      headerSub: 'AIR MAIL',
      title: 'POSTAGE',
      year: '2026',
      palette: PALETTES['prussian-blue'],
      motif: 'waves',
      motifScale: 1.0,
      motifComplexity: 3,
      borderStyle: 'classic-double',
      perforationRadius: 6,
      perforationSpacing: 18,
      postmark: {
        enabled: true,
        city: 'DELHI G.P.O.',
        date: getCurrentPostalDate(),
        rotation: -18,
        wavyBars: true,
        opacity: 0.65,
      },
      texture: true,
    },
  },
  {
    id: 'tokyo-zenith',
    name: 'Tokyo Zenith',
    description: 'Sage Veronese with echoing concentric target rings',
    config: {
      fromLocation: 'Tokyo',
      toLocation: 'Kyoto',
      code: 'TY',
      codePlacement: 'top-left',
      denomination: '¥80',
      headerSub: 'SPECIAL DELIVERY',
      title: 'IMPERIAL POST',
      year: '2026',
      palette: PALETTES['veronese-green'],
      motif: 'concentric',
      motifScale: 1.05,
      motifComplexity: 4,
      borderStyle: 'dashed',
      perforationRadius: 6,
      perforationSpacing: 18,
      postmark: {
        enabled: true,
        city: 'TOKYO CENTRAL',
        date: getCurrentPostalDate(),
        rotation: 12,
        wavyBars: true,
        opacity: 0.6,
      },
      texture: true,
    },
  },
  {
    id: 'manhattan-bauhaus',
    name: 'Penny Black NY',
    description: 'Stark Carbon monochrome with geometric Bauhaus blocks',
    config: {
      fromLocation: 'New York',
      toLocation: 'London',
      code: 'NY',
      codePlacement: 'top-left',
      denomination: '50¢',
      headerSub: 'FIRST CLASS',
      title: 'EXPRESS POST',
      year: '2026',
      palette: PALETTES['penny-black'],
      motif: 'bauhaus',
      motifScale: 1.0,
      motifComplexity: 3,
      borderStyle: 'single',
      perforationRadius: 6,
      perforationSpacing: 17,
      postmark: {
        enabled: false,
        city: 'NEW YORK NY',
        date: getCurrentPostalDate(),
        rotation: -15,
        wavyBars: true,
        opacity: 0.7,
      },
      texture: false,
    },
  },
  {
    id: 'carmine-cairo',
    name: 'Carmine Red',
    description: 'Vibrant Carmine with geometric solar sunburst',
    config: {
      fromLocation: 'Cairo',
      toLocation: 'Rome',
      code: 'CA',
      codePlacement: 'top-left',
      denomination: '15¢',
      headerSub: 'OVERLAND ROUTE',
      title: 'CORREO AÉREO',
      year: '2026',
      palette: PALETTES['carmine-rose'],
      motif: 'sunburst',
      motifScale: 1.0,
      motifComplexity: 3,
      borderStyle: 'ornate',
      perforationRadius: 6.5,
      perforationSpacing: 19,
      postmark: {
        enabled: true,
        city: 'ALEXANDRIA',
        date: getCurrentPostalDate(),
        rotation: -22,
        wavyBars: true,
        opacity: 0.7,
      },
      texture: true,
    },
  },
  {
    id: 'nordic-expedition',
    name: 'Nordic Slate',
    description: 'Muted slate nautical airmail with navigational star',
    config: {
      fromLocation: 'Oslo',
      toLocation: 'Bergen',
      code: 'OS',
      codePlacement: 'top-left',
      denomination: '№ 42',
      headerSub: 'ARCTIC EXPEDITION',
      title: 'REGISTERED',
      year: '2026',
      palette: PALETTES['nordic-slate'],
      motif: 'compass',
      motifScale: 1.1,
      motifComplexity: 3,
      borderStyle: 'classic-double',
      perforationRadius: 6,
      perforationSpacing: 18,
      postmark: {
        enabled: true,
        city: 'OSLO PORT',
        date: getCurrentPostalDate(),
        rotation: 16,
        wavyBars: true,
        opacity: 0.65,
      },
      texture: true,
    },
  },
  {
    id: 'imperial-violet',
    name: 'Imperial Violet',
    description: 'Regal Tyrian violet heraldic star and archival frame',
    config: {
      fromLocation: 'London',
      toLocation: 'Edinburgh',
      code: 'LD',
      codePlacement: 'top-left',
      denomination: '£1',
      headerSub: 'ROYAL POST',
      title: 'CORRESPONDENCE',
      year: '2026',
      palette: PALETTES['tyrian-violet'],
      motif: 'crest',
      motifScale: 1.05,
      motifComplexity: 3,
      borderStyle: 'ornate',
      perforationRadius: 6.5,
      perforationSpacing: 18,
      postmark: {
        enabled: true,
        city: 'LONDON EC1',
        date: getCurrentPostalDate(),
        rotation: -14,
        wavyBars: true,
        opacity: 0.6,
      },
      texture: true,
    },
  },
  {
    id: 'alpine-topography',
    name: 'Bistre Topo',
    description: 'Archival sepia bistre contour elevation curves',
    config: {
      fromLocation: 'Geneva',
      toLocation: 'Zurich',
      code: 'GE',
      codePlacement: 'top-left',
      denomination: 'Fr. 2',
      headerSub: 'TRANS-ALPINE',
      title: 'HELVETIA POST',
      year: '2026',
      palette: PALETTES['sepia-bistre'],
      motif: 'topography',
      motifScale: 1.0,
      motifComplexity: 3,
      borderStyle: 'classic-double',
      perforationRadius: 6,
      perforationSpacing: 18,
      postmark: {
        enabled: true,
        city: 'GENÈVE R.P.',
        date: getCurrentPostalDate(),
        rotation: -25,
        wavyBars: true,
        opacity: 0.7,
      },
      texture: true,
    },
  },
];
